version: "3.9dodocker --ver"

services:
  banners-app:
    image: murashkosv91/banner-app:develop
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 8888:8888
    networks:
      banners:
        aliases:
          - banner-app

  postgresql:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "banners_rotation"
      POSTGRES_USER: "otus"
      POSTGRES_PASSWORD: "otus"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 5455:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otus -d banners_rotation"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      banners:
        aliases:
          - postgresql
networks:
  banners: