// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/banner": {
            "post": {
                "description": "Responds with the instance with added baneer ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Banner"
                ],
                "summary": "Create New Banner",
                "parameters": [
                    {
                        "description": "Banner JSON(ID field could be empty for request)",
                        "name": "banner",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.Banner"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.Banner"
                            }
                        }
                    }
                }
            }
        },
        "/group": {
            "post": {
                "description": "Responds with the instance with added baneer ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Social Group"
                ],
                "summary": "Create New Social Group",
                "parameters": [
                    {
                        "description": "Social Group JSON(ID field could be empty for request)",
                        "name": "sosial_group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.SosialGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.SosialGroup"
                            }
                        }
                    }
                }
            }
        },
        "/slot": {
            "post": {
                "description": "Responds with the instance with added Slot ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slot"
                ],
                "summary": "Create New Slot",
                "parameters": [
                    {
                        "description": "SlotJSON(ID field could be empty for request)",
                        "name": "slot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.Slot"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.Slot"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "storage.Banner": {
            "type": "object",
            "properties": {
                "descr": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "storage.Slot": {
            "type": "object",
            "properties": {
                "descr": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "storage.SosialGroup": {
            "type": "object",
            "properties": {
                "descr": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Banners-Rotation API",
	Description:      "API Server for Banners-Rotation API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
