name: Banner-Roatation-CI

on:
  push:
    branches:
      - "*"

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.23.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.3
          working-directory: .

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.23.1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build service binary
        run: go build -o banner-rotation ./cmd/

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23.1

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: .

      - name: make build
        run: make build
        working-directory: .
      - name: make test
        run: make test
        working-directory: .